### PR TITLE
Gerrit/angular13

### PR DESCRIPTION
**Pull request by ggarbereder**
Update to Angular 13 for https://github.com/microsoft/applicationinsights-angularplugin-js/issues/28

### CODE REVIEW

**Comment by ggarbereder** [comment]
@xiao-lix Any chance to see what's wrong with the build?

**Review by timdeschryver — COMMENTED** [review]
I was taking a look at the repo today so I could start #30 tomorrow.
But I noticed that you beat me to it and already did most of the heavy lifting 🙏
So instead, I looked at this PR and noticed the following:

- the `peerDependencies` should also be updated at https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/package.json#L4-L7
- My guess that the CI is failing is because the `build` command is failing

**Comment by ggarbereder** [comment]
> I was taking a look at the repo today so I could start #30 tomorrow. But I noticed that you beat me to it and already did most of the heavy lifting 🙏 So instead, I looked at this PR and noticed the following:
> 
> * the `peerDependencies` should also be updated at https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/package.json#L4-L7
> * My guess that the CI is failing is because the `build` command is failing
> 
> ```shell
> Configuration doesn't match the required schema.
> Data path "" must NOT have additional properties (whitelistedNonPeerDependencies).
> ```

The property was renamed to `allowedNonPeerDependencies`. Thanks for the hint!

**Comment by MSNev** [comment]
The internal 1DS JavaScript SDK angular plugin check was failing because it was using node v10.x and the changes in this PR (and a few other dependencies) now require 12.x +. I've changed that internal build to use 12.x and I'll submit another PR for this repo to remove 10.x check and then update the "Required" check settings.

**Comment by MSNev** [comment]
FYI - @xiao-lix has left the team

**Review by timdeschryver — COMMENTED** [review]
Could you also update the peer [peer dependency versions](https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/package.json#L4-L7) please?
Otherwise, we'll get warnings when we're installing/updating this libary.

**Comment by ggarbereder** [comment]
> Could you also update the peer [peer dependency versions](https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/package.json#L4-L7) please? Otherwise, we'll get warnings when we're installing/updating this libary.

[Done](https://github.com/ggarbereder/applicationinsights-angularplugin-js/blob/1a3dabdc6a31604953aa1dbb502e557fc71bfe3f/projects/applicationinsights-angularplugin-js/package.json#L5)

**Review by zaslavskyv — APPROVED** [review]

**Review by zaslavskyv — APPROVED** [review]

**Review by idrisfl — APPROVED** [review]

**Comment by idrisfl** [comment]
When can we expect this to be available for release?

**Comment by KaterynaFedorenko** [comment]
Could you please update peerDependencies to the last stable version of Angular - 13.1.2?

**Comment by timdeschryver** [comment]
@KaterynaFedorenko that shouldn't matter, `13.1.2` is a valid version for peerDependency `^13.0.2`

**Review by MSNev — APPROVED** [review]

**Pull request merged**
