### PR TITLE
Setup Husky and Prettier

### PR DESCRIPTION
**Pull request by arturovt**
I didn't run Prettier on the workspace files, maybe you'd want re-visit the rules.

### CODE REVIEW

**Comment by MSNev** [comment]
Internally we are supposed to be using eslint for enforcing / formatting the code. So at this point I don't think we will be able to include this PR.

**Comment by arturovt** [comment]
> Internally we are supposed to be using eslint for enforcing / formatting the code. So at this point I don't think we will be able to include this PR.

Should I then setup `eslint-config-prettier` except?

**Comment by MSNev** [comment]
Potentially, yes. If you look at the main AI project you will see the .eslintrc file that we use and while it uses grunt to "run" it this project doesn't use grunt (at least at the moment) -- which is probably how this repo got missed during initial creation.

**Comment by siyuniu-ms** [comment]
The request is solved in an alternative way in #119.

**Pull request closed without merging**
